services:
  node1:
    build: .
    command: python node.py node1 5000 5001 5002
    ports:
      - "5000:5000"

  node2:
    build: .
    command: python node.py node2 5001 5000 5002
    ports:
      - "5001:5001"

  node3:
    build: .
    command: python node.py node3 5002 5000 5001
    ports:
      - "5002:5002"
